### PR TITLE
Wrap FileInputStream in a BufferedInputStream for ~10x speed improvement

### PR DESCRIPTION
**Pull request by tballison**
Wrap FileInputStream in a BufferedInputStream for ~10x speed improvement

### CODE REVIEW

**Comment by tballison** [comment]
Before the change:
100000 pages in 178282 milliseconds

After the change:
100000 pages in 18394 milliseconds


 ```
@Test
    public void testTiming() throws Exception {
        long start = new Date().getTime();
        File bz2 = new File("C:/.../xyz-pages-articles.xml.bz2");
        WikipediaBz2DumpInputStream wikipediaBz2DumpInputStream = new WikipediaBz2DumpInputStream(bz2.getAbsolutePath());
        String page;
        int counter = 0;
        while ((page = wikipediaBz2DumpInputStream.readNext()) != null) {
            if (counter % 1000 == 0) {
                long elapsed = new Date().getTime()-start;
                System.out.println(counter + " pages in "+ elapsed + " milliseconds");
            }
            counter++;
        }
    }
```

**Comment by lintool** [comment]
@tballison Thanks for the patch... sorry for the delay in looking at it.

**Comment by tballison** [comment]
No problem.  Thank you for this code!  It is supporting Apache Tika's tika-eval module.  We're extracting "common words" from wikipedia as a knuckle-dragging metric to evaluate text extraction/OCR.  Better than nothing, plenty of room for improvement.

**Comment by lintool** [comment]
FYI, v0.5 artifact with this patch published: http://search.maven.org/#search%7Cga%7C1%7Cwikiclean

**Pull request merged**
